version: '3'

services:
  namenode:
    image: hadoop-runtime-arm64:3.3.6
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["/bin/bash", "/config/format-hdfs.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  resourcemanager:
      image: hadoop-runtime-arm64:3.3.6
      container_name: resourcemanager
      depends_on:
        - namenode
      ports:
        - "8088:8088"
      volumes:
        - ./config:/config
      environment:
        - HADOOP_CONF_DIR=/config
      entrypoint: ["yarn", "resourcemanager"]
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "1"
  
  nodemanager1:
    image: hadoop-runtime-arm64:3.3.6
    ports:
      - "8042:8042"
    container_name: nodemanager1
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nodemanager2:
    image: hadoop-runtime-arm64:3.3.6
    ports:
      - "8043:8042"
    container_name: nodemanager2
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nodemanager3:
    image: hadoop-runtime-arm64:3.3.6
    ports:
      - "8044:8042"
    container_name: nodemanager3
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode1:
    image: hadoop-runtime-arm64:3.3.6
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - datanode1-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode2:
    image: hadoop-runtime-arm64:3.3.6
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - datanode2-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode3:
    image: hadoop-runtime-arm64:3.3.6
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - datanode3-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  jobhistory:
    image: hadoop-runtime-arm64:3.3.6
    container_name: jobhistory
    depends_on:
      - namenode
    ports:
      - "19888:19888"
    volumes:
      - ./config:/config
      - jobhistory-logs:/opt/hadoop/logs
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["mapred", "historyserver"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  hive-metastore-db:
    image: postgres
    container_name: hive-metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - metastore-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  hive-metastore:
    image: my-hive-image:4.0.0
    container_name: hive-metastore
    depends_on:
      - hive-metastore-db
      - namenode
    entrypoint: ["/bin/bash", "/opt/hive/conf/init-schema.sh"]
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_PORT: 5432
      HIVE_METASTORE_DB_HOST: hive-metastore-db
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASSWORD: hive
      SERVICE_NAME: metastore
      DB_TYPE: postgres
      SKIP_SCHEMA_INIT: "true"
      HIVE_CONF_DIR: /opt/hive/conf
    ports:
      - "9083:9083"
    volumes:
      - ./config:/opt/hive/conf
      - ./config:/opt/hadoop/etc/hadoop
      - ./config/postgresql-42.7.5.jar:/opt/hive/lib/postgresql-42.7.5.jar
  
  hive-server:
    image: my-hive-image:4.0.0
    container_name: hive-server
    depends_on:
      - namenode
      - hive-metastore
    environment:
      JAVA_OPTS: "-Xmx1G -Dhive.metastore.uris=thrift://hive-metastore:9083"
      SERVICE_NAME: hiveserver2
      DB_DRIVER: postgres
      IS_RESUME: "true"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./config:/opt/hive/conf
      - ./config:/opt/hadoop/etc/hadoop
      - ./config/postgresql-42.7.5.jar:/opt/hive/lib/postgresql-42.7.5.jar
    entrypoint: ["/bin/bash", "/opt/hive/conf/hive-server.sh"]
    command: []
   

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
  jobhistory-logs:
  metastore-db:
