version: '3'

services:
  namenode:
    image: hadoop-runtime-arm64
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["/bin/bash", "/config/format-hdfs.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  resourcemanager:
      image: hadoop-runtime-arm64
      container_name: resourcemanager
      depends_on:
        - namenode
      ports:
        - "8088:8088"
      volumes:
        - ./config:/config
      environment:
        - HADOOP_CONF_DIR=/config
      entrypoint: ["yarn", "resourcemanager"]
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "1"
  
  nodemanager1:
    image: hadoop-runtime-arm64
    ports:
      - "8042:8042"
    container_name: nodemanager1
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nodemanager2:
    image: hadoop-runtime-arm64
    ports:
      - "8043:8042"
    container_name: nodemanager2
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nodemanager3:
    image: hadoop-runtime-arm64
    ports:
      - "8044:8042"
    container_name: nodemanager3
    depends_on:
      - resourcemanager
    volumes:
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["yarn", "nodemanager"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode1:
    image: hadoop-runtime-arm64
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - datanode1-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode2:
    image: hadoop-runtime-arm64
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - datanode2-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  datanode3:
    image: hadoop-runtime-arm64
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - datanode3-data:/hadoop/dfs/data
      - ./config:/config
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["hdfs", "datanode"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  
  jobhistory:
    image: hadoop-runtime-arm64
    container_name: jobhistory
    depends_on:
      - namenode
    ports:
      - "19888:19888"
    volumes:
      - ./config:/config
      - jobhistory-logs:/opt/hadoop/logs
    environment:
      - HADOOP_CONF_DIR=/config
    entrypoint: ["mapred", "historyserver"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data:
  jobhistory-logs:
